<a href="https://colab.research.google.com/github/dongmin-jeong/Python/blob/main/Kaggle_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Kaggle Python Tutorial**

**Lesson 1. Introduction to Python**

In [ ]:
spam_amount=4
viking_song="Spam"*spam_amount
print(viking_song)
#ordering Spam, egg, bacon and Spam

SpamSpamSpamSpam


In [ ]:
if spam_amount>0:
  print("But I don't want any spam!")
  #the colon(:) at the end of the "if" line indicates that a new code block is starting.

But I don't want any spam!


Strings can be marked either by double or single quote character. The * operator can be used to multiply to numbers, but we can also multiply a string by a number.

In [ ]:
type(spam_amount)

int

In [ ]:
type(19.95)

float

In [ ]:
1557//7

222

In [ ]:
1557/7

222.42857142857142

In [ ]:
1557%7

3

In [ ]:
1557**7

22183000448072911857693

We have min, max, abs(the absolute value), ... functions.

In [ ]:
print(float(10))
print(int(3.33))
print(int('807')+1)

10.0
3
808


**Lesson 2. Functions**

1. Help function, help()
2.

In [ ]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [ ]:
round(1/7,10)

0.1428571429

In [ ]:
def least_difference(a, b, c):
  diff1=abs(a-b)
  diff2=abs(b-c)
  diff3=abs(a-c)
  return min(diff1, diff2, diff3)

print(least_difference(10, 100, 198))

90


The docstring is a triple-quoted string that comes immediately after the header of a function. When we call help() on a function, it shows the docstring / 새로 정의한 함수에 대한 설명 ; help 함수를 이용하면 docstring을 그대로 띄워준다.

When you define a new function, you must include the 'return' keyword.

In [ ]:
print(1, 2, 3, sep='<')

1<2<3


In [ ]:
def greet(who="Colin"):
  print("Hello,", who)

greet()
greet(who="Kaggle")
greet(who="World")

Hello, Colin
Hello, Kaggle
Hello, World


In [ ]:
def mod_5(x):
  return x%5

print("Which number is biggest?", max(100, 51, 14), "Which  number is the biggest modulo 5", max(100, 51, 14, key=mod_5), sep='\n')

Which number is biggest?
100
Which  number is the biggest modulo 5
14


In [ ]:
words=["cats", "elephants", "eagles", "tigers"]
print(max(words, key=len))
print(min(words, key=len))

elephants
cats


**Lesson 3. Booleans and Conditions**

Python has a type of variable called bool. It has two possible values: true and false.

In [ ]:
x=True
print(x)
print(type(x))

True
<class 'bool'>


In [ ]:
def can_run_for_president(age):
  return age>=35

print("Can a 30-year-old run for president?", can_run_for_president(30))

Can a 30-year-old run for president? False


In [ ]:
3.0==3
int(3.1)==3

True

In [ ]:
'3'==3

False

In [ ]:
'3'!=3

True

In [ ]:
n=2
n==2
n==3

False

What I want to say: I'm safe from today's weather if i have an umbrella, or if the rain isn't too heavy and i have a hood. Otherwise, I'm sill fine unless it's raining and it's a workday.

In [ ]:
prepared_for_weather=have_umbrella or (rain_level<5 and have_hood) or not (rain_level>0 and is_workday)
#or equivalently, we may write as

prepared_for_weather=(
    have_umbrella
    or (rain_level<5 and have_hood)
    or (not (rain_level>0 and is_workday))
)

Booleans are most useful when combined with conditional statements, using the keywords if, elif, and else.

In [ ]:
def inspect(x):
  if x==0:
    print(x, "is zero")
  elif x>0:
    print(x, "is positive")
  elif x<0:
    print(x, "is negative")
  else:
    print(x, "is unlike anything I've ever seen...")

inspect(-15)
inspect(3)

-15 is negative
3 is positive


**Lesson 4. Lists**

In [ ]:
planets=["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune"]
planets[0]
planets[-1]
planets[0:3]
planets[3:]

['mars', 'jupiter', 'saturn', 'uranus', 'neptune']

In [ ]:
planets[3]="malacandra"
planets

['mercury',
 'venus',
 'earth',
 'malacandra',
 'jupiter',
 'saturn',
 'uranus',
 'neptune']

In [ ]:
len(planets)

8

In [ ]:
sorted(planets)
planets[3]="mars"
primes=[2,3,5,7,11,13]
sum(primes)

41

In [ ]:
max(primes), min(primes)

(13, 2)

In [ ]:
planets.append("pluto")
planets

['mercury',
 'venus',
 'earth',
 'mars',
 'jupiter',
 'saturn',
 'uranus',
 'neptune',
 'pluto']

In [ ]:
planets.pop()
planets

['mercury']

In [ ]:
planets

['mercury']

In [ ]:
planets=["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
planets

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [ ]:
planets.index("Earth")

2

In [ ]:
planets.index("Pluto")

ValueError: 'Pluto' is not in list

In [ ]:
"Pluto" in planets

False

In [ ]:
"Jupiter" in planets

True

In [ ]:
x=0.113434995
x.as_integer_ratio()

(8173852819404385, 72057594037927936)

**Lesson 5. Loops and List Comprehensions**

In [ ]:
planets

['mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune']

In [ ]:
for planet in planets:
  print(planet, end=' ')

mercury venus earth mars jupiter saturn uranus neptune 

The for loop specifies the variable name to use and the set of values to loop over. Here we used the word 'in' to link them together.

In [ ]:
s='steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg=''
for char in s:
  if char.isupper():
    msg=msg+char

print(msg)
#.isupper : 대문자인지 검사하는 method. 예를 들어, "A".isupper() -> True, "a".isupper() -> False이다

HELLO


In [ ]:
for i in range(5):
  print("Doing important work. i=", i)

Doing important work. i= 0
Doing important work. i= 1
Doing important work. i= 2
Doing important work. i= 3
Doing important work. i= 4


In [ ]:
range(10)

range(0, 10)

In [ ]:
for i in range(7):
  print(i)

0
1
2
3
4
5
6


In [ ]:
for i in range(10, 20):
  print(i)

10
11
12
13
14
15
16
17
18
19


In [ ]:
for i, planet in enumerate(planets):
  print(i, planet)

0 mercury
1 venus
2 earth
3 mars
4 jupiter
5 saturn
6 uranus
7 neptune


In [ ]:
i=0
while i<10:
  print(i, end=" ")
  i=i+1

0 1 2 3 4 5 6 7 8 9 

In [ ]:
squares=[n**2 for n in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
squares=[]
for n in range(10):
  squares.append(n**2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
short_planets=[planet for planet in planets if len(planet)<6]
short_planets

['venus', 'earth', 'mars']

In [ ]:
[
    planet.upper()+"!"
    for planet in planets
    if len(planet)<6
]

['VENUS!', 'EARTH!', 'MARS!']

In [ ]:
def count_negatives(nums):
  return len([num for num in nums if num<0])

count_negatives([10, -3, -5, -121, 30, 4])

3

In [ ]:
def count_negatives2(nums):
  return sum([num<0 for num in nums])

count_negatives2([10, 3, 1, -4, -4, -1, -4,-6])

5

**Exercises**

In [ ]:
def has_lucky_number(nums):
  for num in nums:
    if num%7==0:
      return True
    else:
      return False

has_lucky_number([3, 4, 7])
has_lucky_number([])

#Bug : Return causes a function to exit immediately. So this implementation always ran for just one iteration.

In [ ]:
def has_lucky_number(nums):
  for num in nums:
    if num%7==0:
      return True

  return False

has_lucky_number([])
has_lucky_number([1, 4, 14])

True

In [ ]:
help(any)

Help on built-in function any in module builtins:

any(iterable, /)
    Return True if bool(x) is True for any x in the iterable.

    If the iterable is empty, return False.



In [ ]:
def has_lucky_number2(nums):
  return any([num%7==0 for num in nums])

has_lucky_number2([3,14,4,5,6])

True

핵심 : Return을 입력하면 함수는 거기서 즉시 종료된다.

**Lesson 6. Strings and Dictionaries**

String은 sigle or double quotie, ' or "을 이용하여 만든다. 한 개의 string에는 한 종류의 quote만 이용하면 되고, 둘은 기능적으로 동등하다.

In [ ]:
x="Pluto"
y='Pluto'
x==y

True

In [ ]:
'Pluto's a planet'

SyntaxError: unterminated string literal (detected at line 1) (2236334094.py, line 1)

Apstrophe를 쓰는 등 string 내부에서 single quote를 쓸 일이 있다면 string을 double quote로 묶어야 한다. 굳이 single quote로 묶겠다면, backslash를 이용하여 이 문제를 해결할 수 있다.

In [ ]:
'Pluto\'s a planet!'

"Pluto's a planet!"

\n은 줄바꿈 기호.

In [ ]:
hello="hello\nworld"
print(hello)

hello
world


In [ ]:
print("hello", end="")
print("pluto")

hellopluto


In [ ]:
print("hello")
print("pluto")

hello
pluto


In [ ]:
planet="Pluto"
planet[3]

't'

In [ ]:
planet[1:]

'luto'

In [ ]:
[char+"!" for char in planet]

['P!', 'l!', 'u!', 't!', 'o!']

String을 list처럼 다룰 수 있지만(indexing, slicing, loop가 된다) replacing은 안된다.

In [ ]:
planet[0]="B"

TypeError: 'str' object does not support item assignment

In [ ]:
claim="Pluto is a planet!"
claim.upper()

'PLUTO IS A PLANET!'

In [ ]:
claim.lower()

'pluto is a planet!'

In [ ]:
claim.index('net')
#Searching for the first index of a substring ; 여백도 하나의 index로 생각

14

In [ ]:
planet[4]
#planet[5]는 공백이고, 이걸 실행하려고 하면 오류가 나온다.

'o'

In [ ]:
words=claim.split()
words
#.split()이란 method는 string을 띄어쓰기를 기준으로 분류하여 더 작은 string의 list로 만든다.

['Pluto', 'is', 'a', 'planet!']

In [ ]:
datestr="1956-01-31"
year, month, day=datestr.split("-")
month, day, year

('01', '31', '1956')

In [ ]:
"/".join([month, day, year])
#.join()이라는 method는 반대로 적절한 string을 사이에 두고 여러 '단어'를 조합한다.

'01/31/1956'

In [ ]:
year, month, day=datestr.split("-")
"on".join([month, day, year])

'01on31on1956'

In [ ]:
planet="Pluto"
planet+", we miss you.",

('Pluto, we miss you.',)

In [ ]:
x=9
str(x)+" is bigger than 1."

'9 is bigger than 1.'

In [ ]:
"{}, you'll always be the {}th planet to me.".format(planet, x)
#.format()과 {}를 이용하여 type을 무시할 수 있다. 이때 .format()을 format string이라 한다.

"Pluto, you'll always be the 9th planet to me."

In [ ]:
planet="Pluto"
pluto_mass=1.303*10**22
earth_mass=5.9722*10**24
population=1398340430958

"{} weighs about {:.3} kilograms ({:.3%} of Earth's mass). It is home to {:,} Plutonians.".format(planet, pluto_mass, pluto_mass/earth_mass, population)

"Pluto weighs about 1.3e+22 kilograms (0.218% of Earth's mass). It is home to 1,398,340,430,958 Plutonians."

Dictionaries are a built-int Python data structure for mapping keys to values.

In [ ]:
numbers={'one':1, 'two':2, 'three':3}
numbers["one"]

1

In this case, 'one', 'two' and 'three' are the keys and 1, 2 and 3 are their corresponding values.

In [ ]:
numbers['eleven']=11
numbers

{'one': 1, 'two': 2, 'three': 3, 'eleven': 11}

In [ ]:
numbers['one']='Pluto'
numbers

{'one': 'Pluto', 'two': 2, 'three': 3, 'eleven': 11}

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planet_to_initial={planet:planet[0] for planet in planets}
planet_to_initial

{'Mercury': 'M',
 'Venus': 'V',
 'Earth': 'E',
 'Mars': 'M',
 'Jupiter': 'J',
 'Saturn': 'S',
 'Uranus': 'U',
 'Neptune': 'N'}

In [ ]:
#A for loop over a dictionary will loop over its keys.
for k in numbers:
  print("{}={}".format(k, numbers[k]),)

one=Pluto
two=2
three=3
eleven=11


In [ ]:
"/".join(planet_to_initial.values())

'M/V/E/M/J/S/U/N'

In [ ]:
" ".join(planet_to_initial.keys())

'Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune'

In [ ]:
#In Python, an 'item' refers to a key-value pair.
for planet, initial in planet_to_initial.items():
  print("{} begins with \"{}\"".format(planet.rjust(10), initial))
  #.rjust()는 오른쪽 정렬. 비슷하게, .ljust()는 왼쪽 정렬, .cjust()는 가운데 정렬이다.
  #.items()라는 method가 dictionary에서 key, value를 keys, values의 형태로 꺼내줘서 for 뒤에 planet, initial이라는 변수를 지정할 때 그들이 각각 key, value의 값을 가지게 된다.

   Mercury begins with "M"
     Venus begins with "V"
     Earth begins with "E"
      Mars begins with "M"
   Jupiter begins with "J"
    Saturn begins with "S"
    Uranus begins with "U"
   Neptune begins with "N"


In [ ]:
doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
doc_list[1]
doc_list[0]

'The Learn Python Challenge Casino.'

In [ ]:
def word_search(doc_list, keyword):
    """
    Takes a list of documents (each document is a string) and a keyword.
    Returns list of the index values into the original list for all documents
    containing the keyword.

    Example:
    doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
    >>> word_search(doc_list, 'casino')
    >>> [0]
    """
    #나중에 찾은 doc_list의 indice를 저장해두기 위하여 제일 먼저 빈 리스트를 만들어 저장해둔다.
    indices=[]
    keyword=keyword.lower()
    #doc_list를 순회하며(loop) 해당하는 keyword가 있는 index를 찾아 indices에 저장해야하고, 이를 위하여 index와 string을 함께 주는 enumerate함수를 이용한다.
    for i, doc in enumerate(doc_list):
        words=doc.split()
        normalized=[word.strip(".,").lower() for word in words]
        #.strip()은 () 내부의 문자를 제거해주는 method. Method는 서로 연결하여 붙여 쓸 수 있다.
        if keyword in normalized:
            indices.append(i)

    return indices

document_list=["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]

word_search(document_list, "casino")

[0]

**Lesson 7. Working with External Libraries**

In [ ]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [ ]:
#We can see all the names in 'math' using the function, dir()
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [ ]:
math.pi

3.141592653589793

In [ ]:
print("pi to 4 significant digits={:.4}".format(math.pi))

pi to 4 significant digits=3.142


In [ ]:
math.log(81,3)

4.0

In [ ]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.

    If the base is not specified, returns the natural logarithm (base e) of x.



In [ ]:
#We cam import 'math' under a shorter alias to save some typing.
import math as mt
mt.pi

3.141592653589793

In [ ]:
#Or, equivalently, we may write this as
import math
mt=math
print(mt.log(32,2))

5.0


In [ ]:
#Import * makes all the module's variables directly accessible.
from math import *
print(pi, log(32,2))
#오해의 소지가 있는 경우 사용하지 않는 것이(당연히) 좋다.

3.141592653589793 5.0


In [ ]:
from math import *
from numpy import *
print(pi, log(32,2))
#이 경우 math와 numpy 모두에 log라는 함수가 있지만 서로 다른 함수여서 오류가 생긴다.

TypeError: return arrays must be of ArrayType

In [ ]:
from math import log, pi #math 모듈에서 log, pi함수를 '가져온다'
from numpy import asarray #numpy 모듈에서 asarray함수를 '가져온다'

Three tools for understanding strange objects ; how to deal with the various libraries (which are designed for specialized tasks).

In [ ]:
import numpy
rolls=numpy.random.randint(low=1, high=6, size=10)
rolls

array([2, 2, 2, 1, 1, 2, 5, 2, 4, 5])

In [ ]:
type(rolls)
#type() : what is this thing?

numpy.ndarray

In [ ]:
print(dir(rolls))
#dir() : what can I do with it?
#dir()은 rolls 변수 뒤에 붙여 쓸 수 있는 method의 종류를 알려준다.

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [ ]:
rolls.mean()
rolls.max()

np.int64(5)

In [ ]:
rolls.tolist()
#turn the array into a list

[2, 2, 2, 1, 1, 2, 5, 2, 4, 5]

In [ ]:
help(rolls.ravel)
#help() : tell me more

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])

    Return a flattened array.

    Refer to `numpy.ravel` for full documentation.

    See Also
    --------
    numpy.ravel : equivalent function

    ndarray.flat : a flat iterator on the array.



In [ ]:
rolls.ravel()

array([2, 2, 2, 1, 1, 2, 5, 2, 4, 5])

In [ ]:
rolls+10

array([12, 12, 12, 11, 11, 12, 15, 12, 14, 15])

In [ ]:
rolls<=3

array([ True,  True,  True,  True,  True,  True, False,  True, False,
       False])